Fixing Prompt Parser
kharvd/gpt-cli pull request #85
Opened 2024-07-31 09:24 UTC by stevenwalton

Prompt parser will get tripped up if "--" is found anywhere in the prompt and isn't surrounded by specific deliminators. Instead let's force arguments to be at the beginning of the prompt and collect no more arguments after. This way users don't have to place flags inside deliminators and we extend what we can pass to the LLMs.

More context is discussed in #52 with an example.

2024-09-06 01:56 UTC, fn5 commented
@kharvd I ran into an issue with parsing --'s running latest commit https://github.com/kharvd/gpt-cli/commit/d90b1b96c1630dccf6c971ceed4e78bf59d902e9 today. Used this fix and it worked perfectly. Could it be merged?

2024-09-06 02:05 UTC, fn5 commented
@stevenwalton Yup, just saw the stale issue :)

2024-09-06 02:12 UTC, stevenwalton commented
I just synced the branches. If I run into any issues I'll fix or if you find any let me know

2024-09-14 10:12 UTC, williamjameshandley commented
I would also value this being merged. Many thanks for an excellent plugin.

2024-09-15 14:57 UTC, kharvd commented on gptcli/__init__.py
> +__version__ = "0.2.1"
could you please undo this change? i usually bump the version before making a release

2024-09-15 15:01 UTC, kharvd commented
If you are fixing a bug, please add a test case that fails without your fix

2024-09-15 15:01 UTC, kharvd requested changes

2024-09-16 00:27 UTC, stevenwalton commented
Done. Would you like me to update the README? 

Fwiw, someone could make this a bit better if there is a need to have an option that takes in several words as `--myKey "my option"` will not work, but I don't think there is a need for this?

2024-10-12 17:11 UTC, williamjameshandley commented
I would also value this being merged!

2024-11-14 00:40 UTC, sghael requested changes
LGTM (aside from the requested version bump)

2024-11-14 00:40 UTC, sghael commented on gptcli/__init__.py
> +__version__ = "0.2.1"
at this point, this should probably bump to 0.2.2

2024-11-14 03:17 UTC, stevenwalton commented on gptcli/__init__.py
> +__version__ = "0.2.1"
@kharvd had specifically requested that I undo this
https://github.com/kharvd/gpt-cli/pull/85/files/e4598316c999c88b3696cf18cd2db4b5f8b3ba51#r1760065673

I thought I had done it but I guess not. I'm not sure why the version exists if it's not being tracked but `¯\_(ツ)_/¯`

2024-11-14 03:20 UTC, stevenwalton commented
For those that keep asking for the merge, in the mean time you can directly pull to my branch. I'll try to keep it in sync but ping me here or there if I have missed this. 

Idk if @kharvd has abandoned the project but I'll take PRs into mine.

2024-11-17 19:13 UTC, kharvd commented
sorry for the delay here. I'm inclined to remove inline flags functionality altogether rather than force them to appear at the beginning of the prompt. this has obviously been causing more issues than i'd prefer, and personally i just stopped using these flags altogether.

2024-11-17 19:27 UTC, stevenwalton commented
Sure, I can understand that. But as of right now, if anyone uses `--flag` anywhere in their prompt there is a crash. This PR fixes that crash. It is a **_bug fix_**. 

I get that things take time, but then treat this as a patch. It's not a true "fix" because you're going to later throw it out, but my merging at least people won't be crashing while that's figured out. Truthfully, I don't use those flags either. But I did this because I was annoyed at how often I crashed anytime I'd try to submit requests that involved bash lol

2024-11-17 20:33 UTC, kharvd commented
https://github.com/kharvd/gpt-cli/pull/100

2024-11-20 20:09 UTC, closed without merging